[project]
name = "event-scheduler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "apscheduler>=3.11.0",
    "loguru>=0.7.3",
    "pydantic-settings>=2.9.1",
]
